import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/shared/ui/table.tsx';
import {
  type ColumnFiltersState,
  flexRender,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  type SortingState,
  useReactTable,
  type VisibilityState,
} from '@tanstack/react-table';
import { useEffect, useMemo, useState } from 'react';
import { Columns, type TProperty } from './columns.tsx';
import { useUnit } from 'effector-react';
import { $session } from '@/entities/session';
import { fetchArtifacts } from '@/entities/artifacts';
import { fetchProcesses } from '@/entities/processes';
import { Badge } from '@/shared/ui/badge.tsx';

export const TableProperties = () => {
  const [session] = useUnit([$session]);

  const [sorting, setSorting] = useState<SortingState>([]);
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
  const [columnVisibility, setColumnVisibility] = useState<VisibilityState>({});
  const [rowSelection, setRowSelection] = useState({});
  const [pagination, setPagination] = useState({
    pageIndex: 0,
    pageSize: 15,
  });

  const columns = Columns();

  const data: TProperty[] = useMemo(() => {
    return [
      {
        property: 'Status',
        description: 'Work status',
        value: session?.status,
      },
      {
        property: 'Start time',
        description: 'Start time',
        value: session?.startTime && new Date(session.startTime).toLocaleString(),
      },
      {
        property: 'Completed time',
        description: 'Completed time',
        value: session?.completedTime && new Date(session.completedTime).toLocaleString(),
      },
      {
        property: 'Unique id',
        description: 'Session hash (generated by Nextflow)',
        value: session?.uniqueId,
      },
      {
        property: 'Workflow',
        description: 'Workflow (for merging sessions from a single project)',
        value: session?.workflowName && <Badge>{session.workflowName}</Badge>,
      },
      {
        property: 'Script name',
        description: 'Startup script name',
        value: session?.scriptName && <Badge>{session.scriptName}</Badge>,
      },
      {
        property: 'Run name',
        description: 'Run name',
        value: session?.runName && <Badge>{session.runName}</Badge>,
      },
      {
        property: 'Profile',
        description: 'Profile',
        value: session?.profile,
      },
      {
        property: 'Ansi log',
        description: 'Log formatting',
        value: session?.ansiLog,
      },
      {
        property: 'Bin dir',
        description: 'Path to the bin folder',
        value: session?.binDir,
      },
      {
        property: 'Bucket dir',
        description: 'Path to the bucket folder',
        value: session?.bucketDir,
      },
      {
        property: 'Work dir',
        description: 'Path to the working directory',
        value: session?.workDir,
      },
      {
        property: 'Command line',
        description: 'Pipeline launch script',
        value: session?.commandLine,
      },
      {
        property: 'Commit id',
        description: 'Commit SHA hash',
        value: session?.commitId,
      },
      {
        property: 'Pool size',
        description: 'Thread pool size',
        value: session?.poolSize,
      },
      {
        property: 'Resolved config',
        description: 'Final launch configuration',
        value: session?.resolvedConfig,
      },
    ];
  }, [session]);

  const table = useReactTable({
    data: data,
    columns: columns,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    onColumnVisibilityChange: setColumnVisibility,
    onRowSelectionChange: setRowSelection,
    onPaginationChange: setPagination,
    state: {
      sorting,
      columnFilters,
      columnVisibility,
      rowSelection,
      pagination: pagination,
    },
  });

  useEffect(() => {
    if (!session) {
      return;
    }

    fetchProcesses(session.id);
    fetchArtifacts(session.id);
  }, [session]);

  return (
    <div className={'border rounded-lg overflow-hidden'}>
      <Table>
        <TableHeader>
          {table.getHeaderGroups().map(headerGroup => (
            <TableRow key={headerGroup.id}>
              {headerGroup.headers.map(header => {
                return (
                  <TableHead key={header.id}>
                    {header.isPlaceholder
                      ? null
                      : flexRender(header.column.columnDef.header, header.getContext())}
                  </TableHead>
                );
              })}
            </TableRow>
          ))}
        </TableHeader>
        <TableBody>
          {table.getRowModel().rows?.length ? (
            table.getRowModel().rows.map(row => (
              <TableRow key={row.id} data-state={row.getIsSelected() && 'selected'}>
                {row.getVisibleCells().map(cell => (
                  <TableCell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </TableCell>
                ))}
              </TableRow>
            ))
          ) : (
            <TableRow>
              <TableCell colSpan={Columns.length} className="h-24 text-center">
                No results.
              </TableCell>
            </TableRow>
          )}
        </TableBody>
      </Table>
    </div>
  );
};
